/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-primary-fixed": "#001b3c",
        "on-surface": "#181c1e",
        "surface-variant": "#e0e3e5",
        "surface-container-lowest": "#ffffff",
        "on-background": "#181c1e",
        "inverse-on-surface": "#eef1f3",
        "primary-fixed-dim": "#adc7f7",
        "on-tertiary-container": "#cb9524",
        "tertiary": "#2d1d00",
        "surface": "#f7fafc",
        "on-tertiary-fixed": "#271900",
        "outline-variant": "#c4c6cf",
        "amber-soft": "rgba(214, 158, 46, 0.1)",
        "inverse-primary": "#adc7f7",
        "on-error": "#ffffff",
        "surface-container": "#ebeef0",
        "on-primary": "#ffffff",
        "surface-container-low": "#f1f4f6",
        "on-secondary": "#ffffff",
        "primary-container": "#1a365d",
        "on-surface-variant": "#43474e",
        "surface-container-high": "#e5e9eb",
        "background": "#f7fafc",
        "error-container": "#ffdad6",
        "on-tertiary-fixed-variant": "#5f4100",
        "on-tertiary": "#ffffff",
        "error": "#ba1a1a",
        "surface-dim": "#d7dadc",
        "on-primary-container": "#86a0cd",
        "inverse-surface": "#2d3133",
        "surface-bright": "#f7fafc",
        "on-secondary-container": "#00723f",
        "tertiary-container": "#493100",
        "secondary-container": "#85f6ad",
        "primary": "#002045",
        "outline": "#74777f",
        "on-error-container": "#93000a",
        "surface-tint": "#455f88",
        "secondary": "#006d3c",
        "success-green": "#48BB78",
        "secondary-fixed": "#88f9b0",
        "primary-fixed": "#d6e3ff",
        "on-primary-fixed-variant": "#2d476f",
        "tertiary-fixed-dim": "#f8bc4b",
        "tertiary-fixed": "#ffdeaa",
        "secondary-fixed-dim": "#6bdc96",
        "on-secondary-fixed": "#00210f",
        "on-secondary-fixed-variant": "#00522c",
        "surface-container-highest": "#e0e3e5",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        full: "9999px",
      },
      spacing: {
        "margin-desktop": "64px",
        "container-max": "1200px",
        "margin-mobile": "16px",
        unit: "8px",
        gutter: "24px",
      },
      fontFamily: {
        inter: ["Inter", "sans-serif"],
      },
      fontSize: {
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "600" }],
        "headline-lg-mobile": ["28px", { lineHeight: "36px", fontWeight: "700" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.05em", fontWeight: "500" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
}
